apiVersion: apps/v1
kind: Deployment 
metadata:
  name: streamlit-python-app
  labels:
    app: python-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template: 
    metadata:
      labels: 
        app: python-app
        tier: frontend
    spec: 
      containers: 
        - name: python-app
          image: tarunashwini/survey_form:v1.3
          volumeMounts:
            - mountPath: /mnt/data
              name: survey-form-data
          ports:
            - containerPort: 8501
      volumes:
        - name: survey-form-data
          persistentVolumeClaim:
            claimName: survey-form-pvc

---
apiVersion: v1
kind: Service 
metadata:
  name: tarun-python-service
  labels:
    app: python-app
    tier: frontend  
spec:
  type: LoadBalancer 
  selector:
    app: python-app
  ports: 
    - name: http
      port: 8501
      targetPort: 8501

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: survey-form-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
